services:
  api:
    container_name: fooddash_api
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    image: fooddash
    networks:
      - webnet
    restart: always
    env_file:
      - .env

  db:
    container_name: fooddash_db
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_EXPOSED_PORT}:5432'
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  webnet:
