services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: fooddash
    volumes:
      - ./postgres:/var/lib/postgresql/data

# version: '3.5'

# services:
#   db:
#     image: postgres:14.3
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     container_name: fooddash
#     volumes:
#       - ./postgres:/var/lib/postgresql/data
#     ports:
#       - '${DB_PORT}:5432'

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nest-docker-postgres
#     environment:
#       - PORT=${PORT}
#       - DB_HOST=db
#       - DB_PORT=5432 # Este sigue siendo el puerto interno del contenedor
#       - DB_NAME=${DB_NAME}
#       - DB_USERMAME=${DB_USERMAME}
#       - DB_PASSWORD=${DB_PASSWORD}
#     ports:
#       - '${PORT}:${PORT}'
#     depends_on:
#       - db
#     volumes:
#       - ./src:/app/src
